### ISSUE TITLE
Training error 'module' object has no attribute 'downsample'

### ISSUE THREAD

**Issue by VirginiaMenezes** [dimatura/voxnet#28]
When I am trying to run the **train.py** file for training, I am getting the error **'module' object has no attribute 'downsample'** 
I read that downsample in theano.tensor.signal import downsample has been moved to pool module.
But which function is equivalent in pool is equivalent to DownsampleFactorMax in downsample.

Please help ASAP.
```
Traceback (most recent call last):
  File "train.py", line 182, in <module>
    main(args)
  File "train.py", line 135, in main
    tfuncs, tvars = make_training_functions(cfg, model)
  File "train.py", line 31, in make_training_functions
    out = lasagne.layers.get_output(l_out, X)
  File "/usr/local/lib/python2.7/dist-packages/lasagne/layers/helper.py", line 185, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/home/nvidia/virginia/voxnet/voxnet/layers.py", line 244, in get_output_for
    out = max_pool_3d(input, self.pool_shape)
  File "/home/nvidia/virginia/voxnet/voxnet/max_pool_3d.py", line 72, in max_pool_3d
    op = T.signal.downsample.DownsampleFactorMax((ds[1], ds[2]), ignore_border)
AttributeError: 'module' object has no attribute 'downsample'

```

**Comment by CATHUR** [comment]
I also encountered this situation, and I changed the source code as follows:
op = T.signal.pool.Pool((ds[1], ds[2]), ignore_border)

**Comment by stephencuinujia** [comment]
I got 
ValueError: Pool mode parameter only support 'max', 'sum', 'average_inc_pad' and 'average_exc_pad'. Got False

After change to 
op = T.signal.pool.Pool((ds[1], ds[2]), ignore_border)

Any idea?

**Comment by merium** [comment]
I solved the same issue by switching to theano 0.8.2

**Comment by buemi** [comment]
I solved this issue in theano 1.0.1 by replacing the following statements:

_op = T.signal.downsample.DownsampleFactorMax((ds[1], ds[2]), ignore_border)
output = op(input_4D)_

with these:

_op = T.signal.pool.Pool(ignore_border) 
output = op(input_4D, ws=(ds[1], ds[2]))_ 

And the other call to _DownsampleFactorMax_ in the same way.

**Comment by claell** [comment]
This is apparently caused by Theano moving `downsample` to a different package. I think Lasagne 0.1 uses the old location, which only works with Theano 0.8.2 or lower. Unfortunately there does not seem to be a more updated version of Lasagne.
